### ISSUE TITLE
SCANG error in class(genotype)=="dgCMatrix" Rversion 4.2.0

### ISSUE THREAD

**Issue by GeorgeKoliopanos** [xihaoli/STAARpipeline#1]
Trying to use Dynamic_Window_SCANG.r function I run into an error come from comparison class(genotype)=="dgCMatrix". While, going deeper into this I found that the problem is that genotype object (= Geno) has two classes "matrix" "array" and the comparison cannot be done. The issue with the two classes, appears after R version 4.0.0 (https://cran.r-project.org/doc/manuals/r-release/NEWS.html).

**Comment by xihaoli** [comment]
Hi George,

Thank you for the information. We have fixed this issue in the [SCANG package](https://github.com/zilinli1988/SCANG) accordingly.

Best,
Xihao
