### ISSUE TITLE
STAARPipeline for imbalanced binary phenotypes

### ISSUE THREAD

**Issue by Andi963** [xihaoli/STAARpipeline#10]
Hello and first many thanks for generating such a nice and useful pipeline!

I've seen that you recently improved STAAR according to imbalanced binary scenarios. Is this already integrated in the STAARPipeline approach?

Many thanks in advance!

Best
Andi

**Comment by xihaoli** [comment]
Hi Andi,

Thank you for your message. We have a local copy of the updated `STAARpipeline` and `STAARpipelineSummary` packages readily available, and we are currently updating the GitHub repositories. The updated repositories of `STAARpipeline` and `STAARpipelineSummary` should be ready today or tomorrow.

If you would like to have a local copy and install from source, please send me an email.

Best,
Xihao

**Comment by xihaoli** [comment]
Hi Andi, the `STAARpipeline` package has now been updated to account for dichotomous traits with imbalanced case-control ratios.
