### ISSUE TITLE
Forced relatedness in null model despite NULL kins

### ISSUE THREAD

**Issue by hsolleder** [xihaoli/STAARpipeline#15]
Hi all,

from reading and trying to understand/run the pipeline, the relatedness parameter is set to TRUE during the creation of the null model object, irrespective of whether `kins` is NULL or a matrix, c.f. lines 159 in `fit_nullmodel.R`

As a direct consequence, `STAAR` will call `STAAR_O_SMMAT` (since `sparse_kins` is set to TRUE, c.f. line 81 in `fit_nullmodel.R`) rather than `STAAR_O`. From the outside, it would thus appear that a function designed to account for population structure/relatedness is called despite no information about the population structure/relatedness being provided, which is surprising. 

Was this intended? Or should the `relatedness` element of `obj_nullmodel` be set to FALSE, such that `STAAR_O` would be called?

**Comment by xihaoli** [comment]
Hi @hsolleder,

Thanks for your question, and this is intended. Initially, in developing [STAAR package](https://github.com/xihaoli/STAAR), we considered the cases with/without `relatedness` separately. Later on, when we were developing the [STAARpipeline package](https://github.com/xihaoli/STAARpipeline), we decided to unify the cases with/without `relatedness` by both storing the objects of `Sigma_i`, `Sigma_iX` and `cov` in `obj_nullmodel`. Specifically, the case of no relatedness can be considered a special case of a sparse GRM.

Therefore, although `sparse_kins` is now set to TRUE in both cases, it can correctly account for settings with/without `relatedness`.

Hope this is clear.

Best,
Xihao

**Comment by hsolleder** [comment]
Dear Xihao, 

Thank you for your rapid and clear answer to my question.

Best
