### ISSUE TITLE
docker for STAARpipeline

### ISSUE THREAD

**Issue by akhilpampana** [xihaoli/STAARpipeline#17]
Hello,

I am trying to see if there have been an implementation of this pipeline in the google cloud platform or if any docker has been available for this to perform the same in google cloud as I have seen the same in the Dnanexus platform for ukbiobank.

Regards
Akhil

**Comment by xihaoli** [comment]
Hi Akhil,

Yes, there is an implementation for all STAARpipeline-related apps in the Google Cloud platform (see [here](https://platform.sb.biodatacatalyst.nhlbi.nih.gov/public/apps/admin/sbg-public-data/staarpipeline-0-9-6)). If you have any questions, please feel free to [reach out](mailto:Lea.Lenhardt.Ackovic@velsera.com;xihaoli@unc.edu).

Thanks,
Xihao

**Comment by akhilpampana** [comment]
have this been implemented in all of us workbench? I see seven bridges there. I will see if I can try the same in all of us platform.

**Comment by jwilliams10** [comment]
@akhilpampana, Hello,

I have implemented STAARpipeline in the all of us platform. All of Us allows two types of jobs interactive and batch submitted. In interactive jobs, STAARpipeline will need to be installed inside the job "install.packages()" and if you keep your persistent disk then your interactive job will always have access to the staar-pipeline. In batch submitted jobs, you can either use a publicly available docker that has STAARpipeline installed or at the start of each submitted job, install the package in a similar manner. To implement STAARpipeline once installed, I followed the scripts in the STAARpipeline Tutorial (https://github.com/xihaoli/STAARpipeline-Tutorial). There is no command line tool in All of Us, just R Scripts in either interactive or batch submitted jobs.

**Comment by xihaoli** [comment]
Hi @akhilpampana,

I am closing this issue for now as it's been answered by @jwilliams10. Please feel free to reopen it if you have any additional questions.

Best,
Xihao
