### ISSUE TITLE
Burden effects for all genes of a category

### ISSUE THREAD

**Issue by akhilpampana** [xihaoli/STAARpipeline#18]
Hello,

I am trying to extract burden effects for all genes present in the rvas results rather than significant genes to perform meta-analysis? Is it possible to do so if so what is the potential way to accomplish it?

Regards
Akhil

**Comment by xihaoli** [comment]
Hi @akhilpampana,

For rare variant meta-analysis, please refer to the `MetaSTAAR` [method](https://doi.org/10.1038/s41588-022-01225-6) and [package](https://github.com/xihaoli/MetaSTAAR).

Let me know if you have any questions.

Best,
Xihao
