### ISSUE TITLE
regarding STAAR Sliding Window 

### ISSUE THREAD

**Issue by ryshi06** [xihaoli/STAARpipeline#21]
Hello, I was performing the rare variant analysis using the sliding window approach. When running the pre-built pipeline, I have several questions that need your help. Thank you!

1. For each loop in `kk`, I get the output saying 

`[1] 1
of selected samples: 1,466
of selected variants: 437
Error : eig_sym(): decomposition failed
of selected samples: 1,966
of selected variants: 5,335,313`, 

where the 437 should be the variants within the window, and the 5,335,313 is the total number of variants. 1) based on this output, my first question comes from the error message. I followed an old issue to check. There is no missing in the genotype matrix, and I updated the Rcpp to the latest version. But I still get this error message. 2) secondly, by run the source code line by line, I am a little confused since I did not see a line to subset genotype matrix by the SNPs in the window region. Can you please tell me which line in which source code gives this subset? I appreciate it a lot!

2. In the pre-set option "type", I did not find a detailed explanation on using either "single" or "multiple". Based on the instruction, the default is "single", but in the pipeline, "multiple" is used. I am wondering can you give me an example of when to use "single" and when to use "multiple"? 

3. Just curious, I am wondering if the sliding window approach can be applied to non-coding variants only?

Thank you!
Ruyu

**Comment by ryshi06** [comment]
`> packageVersion("Rcpp")
[1] ‘1.0.13’
> packageVersion("RcppArmadillo")
[1] ‘14.0.0.1’`

**Comment by xihaoli** [comment]
Hi Ruyu,

Thanks for asking. For your questions:
1. It seems like there exist missing values in your variant annotations. Have you used FAVORannotator to annotate your data properly? Also, what did you use for the `variant_type` parameter? For a quick check, you can set `Use_annotation_weights = FALSE` and see if you still have this error;
2. The default type of `single` is used when you only want to query a specific sliding window with fixed start and end locations. If you want to perform a genome-wide scan, typically you would use `multiple`, and the logic is you only extract a longer region of the genotype once and subset to each sliding window to improve computation efficiency;
3. Sliding window is applied to both coding and noncoding variants, as it may cover the exonic/intronic regions in addition to the intergenic regions.

Best,
Xihao

**Comment by ryshi06** [comment]
Hi Dr. Li, 

Yes, I used the pre-built FAVOR annotation pipeline and everything went well. I also did the non-coding rare variant analysis without any unexpected errors with `Use_annotation_weights <- TRUE.` I set `variant_type <- "SNV"`. 

After setting `Use_annotation_weights <- FALSE`, I get rid of this error - Does this suggest that there might be an issue with the annotation for coding region variants? If so, should I re-perform the entire annotation? 

Thank you!

Best,
Ruyu

**Comment by xihaoli** [comment]
Hi Ruyu,

This indicated that some annotations were missing for your variants, but that shouldn't be the case. You can add one annotation score at a time to check which annotations have missing values. Btw, which FAVOR database were you using?

Best,
Xihao

**Comment by ryshi06** [comment]
I downloaded the FAVOR annotation reference file from `https://dataverse.harvard.edu/api/access/datafile` for chromosome 1:22. 

Thanks for the advice! I will try to figure out which annotation is missing here. So basically, the missing annotation leads to a missing weight, and generate the error, right?

Ruyu

**Comment by ryshi06** [comment]
`## URLs <- data.frame(chr = c(1:22),
##                    URL = c("https://dataverse.harvard.edu/api/access/datafile/6170506",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170501",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170502",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170521",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170511",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170516",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170505",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170513",
##                            "https://dataverse.harvard.edu/api/access/datafile/6165867",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170507",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170517",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170520",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170503",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170509",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170515",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170518",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170510",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170508",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170514",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170512",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170519",
##                            "https://dataverse.harvard.edu/api/access/datafile/6170504"))

## for (chr in c(1:22)){
##   URL <- URLs[chr, "URL"]
##   system(paste0("wget --progress=bar:force:noscroll ", URLs[chr, "URL"]))
##   system(paste0("tar -xvf ", gsub(".*?([0-9]+).*", "\\1", URL)))
## }`

This is the command I used to download the references.

**Comment by xihaoli** [comment]
This looks alright. We have already taken care of missing values in the FAVOR database, so I don't expect you'll still have missing values. It's a good idea to figure out which annotation is missing in your case.

**Comment by ryshi06** [comment]
Sure, I will figure out which is missing and get back to you. Thank you!

**Comment by ryshi06** [comment]
Hi, sorry for the late update. I tried to run the chunk of extracting annotation scores with the following command:

`
length(Annotation_name)

for(k in 1:length(Annotation_name))
{
  if(Annotation_name[k]%in%Annotation_name_catalog$name)
  {
    Anno.Int.PHRED.sub.name <- c(Anno.Int.PHRED.sub.name,Annotation_name[k])
    Annotation.PHRED <- seqGetData(genofile, paste0(Annotation_dir,Annotation_name_catalog$dir[which(Annotation_name_catalog$name==Annotation_name[k])]))
    
    if(Annotation_name[k]=="CADD")
    {
      Annotation.PHRED[is.na(Annotation.PHRED)] <- 0
    }
    
    if(Annotation_name[k]=="aPC.LocalDiversity")
    {
      Annotation.PHRED.2 <- -10*log10(1-10^(-Annotation.PHRED/10))
      Annotation.PHRED <- cbind(Annotation.PHRED,Annotation.PHRED.2)
      Anno.Int.PHRED.sub.name <- c(Anno.Int.PHRED.sub.name,paste0(Annotation_name[k],"(-)"))
    }
    Anno.Int.PHRED.sub <- cbind(Anno.Int.PHRED.sub,Annotation.PHRED)
  }
}`

from this chunk, I do get several missing values from all categories except for CADD (since the missings in CADD is replaced by 0 in this case) for some SNVs. 

The categories I am using are:

`> Annotation_name
 [1] "CADD"                        "LINSIGHT"                    "FATHMM.XF"                  
 [4] "aPC.EpigeneticActive"        "aPC.EpigeneticRepressed"     "aPC.EpigeneticTranscription"
 [7] "aPC.Conservation"            "aPC.LocalDiversity"          "aPC.Mappability"            
[10] "aPC.TF"                      "aPC.Protein"      `

Am I missing something here?

**Comment by ryshi06** [comment]
Here are the top 100 rows of the chr22 annotation output. I am not sure if this may help. 

[top100_from_Anno_chr22_STAARpipeline.csv](https://github.com/user-attachments/files/16931306/top100_from_Anno_chr22_STAARpipeline.csv)

**Comment by xihaoli** [comment]
Hi Ruyu,

Thanks for taking into this. I am wondering what variants (`chr-pos-ref-alt`) correspond to the NA's in your `annotation_NAs_example.txt` above. Note that indels may not have the complete annotation scores as SNVs. However, since you set `variant_type <- "SNV" (that's why I asked in the beginning), I am wondering why you would still have potential NA for SNVs.

Best,
Xihao

**Comment by ryshi06** [comment]
`grep "105020628" Anno_chr1_STAARpipeline.csv
1-105020628-A-G,,,,,,,,,,,,,,,,,,,,,`

I extract the first one from the missing fields, and above is the FAVOR annotation output. It seems like I do not have any annotated information available for this specific variant.

**Comment by ryshi06** [comment]
In the mean time, I have a quick question on assigning the `arrayid` - if I want to loop over in the interactive R workspace instead of submitting as a batch job, how should I assign the `arrayid` to make it properly loop over chromosome 1 to 22? Thanks!

**Comment by xihaoli** [comment]
Is your genome coordinate on build 38? I tried to search this variant: `1-105020628-A-G`, but it is not showing either in FAVOR (https://favor.genohub.org/) or Bravo (https://bravo.sph.umich.edu/). The closest variant I can find is `1-105020626-A-G`. Could you please double check your data?

**Comment by ryshi06** [comment]
Yes, it is on build 38. 

In the bim file: `1	rs12404190	0	105020628	G	A`
And then I can find it in dbSNP as the figure pasted below:

<img width="446" alt="Screenshot 2024-09-09 at 10 19 41 AM" src="https://github.com/user-attachments/assets/681f51db-ae33-4e0e-9398-5f437dc356d4">

**Comment by xihaoli** [comment]
Currently, `arrayid` is designed for batch submission. Do you want to submit one job for each chromosome? If so, you could use `mclapply()` to parallel the task internally. An example for [STAARpipeline](https://github.com/li-lab-genetics/staarpipeline-rap/blob/main/resources/home/dnanexus/staarpipeline.R) is here and you can adapt to your need.

**Comment by xihaoli** [comment]
Thanks for sharing. In this case, your variant identifier should be `1-105020628-G-A` rather than `1-105020628-A-G`, as indicated in the screenshot. I just searched on FAVOR and noticed that `1-105020628-G-A` does exist. Hence, you should flip the ref and alt alleles before annotating for these variants.

**Comment by ryshi06** [comment]
Thank you so much! Does FAVOR provide a function to check the flip before the annotation? If not, do you have a recommended way to check all the allele in the Plink file set? Thank you!

**Comment by ryshi06** [comment]
Thank you so much for your detailed explanations and help! I will fix the flip first and see if I can run everything smoothly. Have a good day!

**Comment by xihaoli** [comment]
No problem, I am wondering if your file is showing: `1 rs12404190 0 105020628 G A`, why the variant has been coded as `1-105020628-A-G` at the first place?

**Comment by ryshi06** [comment]
The bim file has G as the minor and A as the major allele, so when assigning the new ID, it recognizes `G` as the alternative allele, and `A` as the ref?

**Comment by ryshi06** [comment]
I followed the pipeline to set the variant id using the following command:
`bed.fn <- paste0("/ix/kfan/Ruyu/Pib_WGS_GWAS/Data/Genotype/by_Chromosome/PiB_WGS_Annota_QCed-Chr",chr,".bed")
  bim.fn <- paste0("/ix/kfan/Ruyu/Pib_WGS_GWAS/Data/Genotype/by_Chromosome/PiB_WGS_Annota_QCed-Chr",chr,".bim")
  fam.fn <- paste0("/ix/kfan/Ruyu/Pib_WGS_GWAS/Data/Genotype/by_Chromosome/PiB_WGS_Annota_QCed-Chr",chr,".fam")
  
  # output to gds
  out.gdsfn <- paste0("/ix/kfan/Ruyu/Pib_WGS_GWAS/Data/Genotype/by_Chromosome/PiB_WGS_Annota_QCed-Chr",chr,".gds")
  SeqArray::seqBED2GDS(bed.fn, fam.fn, bim.fn, out.gdsfn, compress.geno="LZMA_RA",
                       compress.annotation="LZMA_RA", chr.conv=TRUE, 
                       optimize=TRUE, digest=TRUE, parallel=FALSE, verbose=TRUE)
  print(paste0("Chr",chr," conversion done."))`
, and then
`gds.path <- paste0("/ix/kfan/Ruyu/Pib_WGS_GWAS/Data/Genotype/by_Chromosome/PiB_WGS_Annota_QCed-Chr",chr,".gds")
  genofile <- seqOpen(gds.path)
  
  CHR <- as.numeric(seqGetData(genofile, "chromosome"))
  position <- as.integer(seqGetData(genofile, "position"))
  REF <- as.character(seqGetData(genofile, "$ref"))
  ALT <- as.character(seqGetData(genofile, "$alt"))`

and I did not manually assign the ref/alt, so I am not sure why the bim file shows `1 rs12404190 0 105020628 G A` while the output id is `1-105020628-A-G`.

**Comment by xihaoli** [comment]
Okay, then this might be arising from `seqBED2GDS()` in `SeqArray` but not from FAVOR. Feel free to file an issue [here](https://github.com/zhengxwen/SeqArray/issues).

**Comment by ryshi06** [comment]
Thank you. Issue submitted to `SeqArray`. 

Since the issue comes from the `SeqArray`, I will use the FAVOR database as the reference to manually flip the wrong IDs and re-run the annotation to see if everything works.

**Comment by xihaoli** [comment]
Sounds good!

**Comment by ryshi06** [comment]
Hello Dr. Li, 

A late update on our previous conversation. I manually flip the SNV alleles that failed to be annotated before, and I can see the annotation is successful. 

However, when I tried to run the sliding window analysis this time, I found the deletions, like `22-50566074-T-*` will be recognized as SNV as well. By running the source code line by line, I added `biallelic = TRUE` to the `isSNV` command and that does not help. Do you have any ideas that how can I delete those variants in the analysis? 

Thank you!

**Comment by xihaoli** [comment]
Hi @ryshi06,

Thanks for letting me know. For variants like this (`22-50566074-T-*`), you can follow Note 2 of the [tutorial](https://github.com/xihaoli/STAARpipeline-Tutorial#generate-genomic-data-structure-gds-file) by defining a new QC label, where you keep the original QC label, and then set those variants with alternative allele being missing ("*") to FAIL. This way you can run STAARpipeline by specifying your new QC label to exclude those variants from the analysis.

Best,
Xihao

**Comment by ryshi06** [comment]
Adding another QC filter works! Thank you for all the help!

Best,
Ruyu

**Comment by xihaoli** [comment]
No problem, and glad to hear. I'm closing this case for now. Please feel free to reopen if you have any follow-up questions.
