### ISSUE TITLE
Regarding the cMAC value

### ISSUE THREAD

**Issue by ryshi06** [xihaoli/STAARpipeline#23]
Hello Dr. Li, 

Thanks again for this great package. I have a quick question that why some cMAC output has decimal points. Based on my understanding, this might be caused by the genotype imputation, but I cannot find any related scripts illustrating this. Can you please help me clarify this. Thank you!

Best,
Ruyu

**Comment by xihaoli** [comment]
Hi Ruyu,

Thanks for reaching out. Yes, if after your variant QC steps, there are still variants with missing genotypes in your dataset, STAARpipeline will then impute either by mean dosage (default) or the minor allele across all samples (see [here](https://github.com/xihaoli/STAARpipeline/blob/main/R/Gene_Centric_Coding.R#L30) for an example). Thus, if you are using "mean" imputation, your `cMAC` may not be an integer.

Best,
Xihao

**Comment by xihaoli** [comment]
Hi Ruyu,

I am closing this case for now. Please feel free to reopen it if you have any additional questions.

Best,
Xihao
