### ISSUE TITLE
preinstall packages

### ISSUE THREAD

**Issue by JianqiaoWang** [xihaoli/STAARpipeline#3]
I would suggest add following lines for the preinstall packages. These packages seem need to be installed manually in the order (like STAAR depend on SeqArray). 
 
BiocManager::install("SeqArray")
BiocManager::install("SeqVarTools")
devtools::install_github("hanchenphd/GMMAT")
BiocManager::install("GENESIS")
devtools::install_github("xihaoli/STAAR",ref="main")
BiocManager::install("TxDb.Hsapiens.UCSC.hg38.knownGene")
BiocManager::install("GenomicFeatures")
devtools::install_github("zilinli1988/SCANG")

I am also get confused for the Intel Math Kernel Library.

**Comment by xihaoli** [comment]
Hi Jianqiao,

Thank you for your suggestions. Alternatively, you could also pull the [STAARpipeline docker image](https://hub.docker.com/repository/docker/zilinli/staarpipeline), which includes an R built with Intel MKL and all STAAR-related packages (STAAR, SCANG, STAARpipeline, STAARpipelineSummary) pre-installed.

Best,
Xihao
