### ISSUE TITLE
Account for population frequency

### ISSUE THREAD

**Issue by ionicbond2005** [xihaoli/STAARpipeline#4]
Hi Dr. Li

In determining rare variant in the gene-centric coding pipeline, does STAARpipeline use allelic frequency information from population database such as gnomAD, 1000 Genome, ESP6500, etc to determine whether the variant in exonic region is also rare in all populations? Also, how do you define 'rare' in all other pipeline? Like rare in the cohort or rare in the population databases?

Thank you very much

**Comment by xihaoli** [comment]
Hi,

Thank you for your question. In the gene-centric coding and all other pipelines, STAARpipeline calculates the allele frequency of each variant in the current study/cohort to determine whether it is a rare variant or not.

Best,
Xihao
