### ISSUE TITLE
Are there provide a toy data?

### ISSUE THREAD

**Issue by DamienTan** [xihaoli/STAARpipeline#5]
Hi, Dr. li

thanks you for the tool, It looks handy for users to go through the GWAS analysis. And I want to know there are provide a toy data for a new guy, like me.

Looking forward your reply!

**Comment by xihaoli** [comment]
Hi Damien,

Thanks for your comment. To get started with STAAR and STAARpipeline, feel free to go through [this tutorial](https://htmlpreview.github.io/?https://github.com/xihaoli/STAAR/blob/master/docs/STAAR_vignette.html).

Hope this helps.

Best,
Xihao

**Comment by DamienTan** [comment]
> Hi Damien,
> 
> Thanks for your comment. To get started with STAAR and STAARpipeline, feel free to go through [this tutorial](https://htmlpreview.github.io/?https://github.com/xihaoli/STAAR/blob/master/docs/STAAR_vignette.html).
> 
> Hope this helps.
> 
> Best, Xihao

Roger that! 
thanks Dr. Li
