### ISSUE TITLE
How do other species generate the variants list to be annotated?

### ISSUE THREAD

**Issue by nainai77** [xihaoli/STAARpipeline#6]
Hi,

I want to use STAARpipeline to detect rare variation information in plants. I have my own vcf file and its annotation information. How can I generate the variants list to be annotated? I read the FAVORdatabase_chrsplit.csv in the example, and I don't know what it means, so I don't know how to start.

Looking forward to your reply! 

Ayn

**Comment by xihaoli** [comment]
Hi Ayn,

Thanks for your question. The first step of using STAARpipeline is to convert your vcf file to SeqArray GDS format. For more details on usage, please see the R/Bioconductor package [SeqArray](https://bioconductor.org/packages/release/bioc/html/SeqArray.html) [[manual](https://bioconductor.org/packages/release/bioc/manuals/SeqArray/man/SeqArray.pdf)]. Then, FAVORannotator can annotate your GDS file into the annotated GDS (aGDS) files.

On another comment, the annotation database from FAVOR database (and FAVORdatabase_chrsplit.csv) is based on NCBI GRCh38/UCSC hg38. Given that your genotype data and its annotation are from plants, you may consider writing a customized wrapper and running [STAAR](https://github.com/xihaoli/STAAR) or [STAARpipeline](https://github.com/xihaoli/STAARpipeline) directly, as STAAR/STAARpipeline is a general method for phenotype-genotype association analysis.

Hope this helps.

Best,
Xihao

**Comment by xihaoli** [comment]
Hi Ayn,

Thanks for your question. The first step of using STAARpipeline is to convert your vcf file to SeqArray GDS format. For more details on usage, please see the R/Bioconductor package [SeqArray](https://bioconductor.org/packages/release/bioc/html/SeqArray.html) [[manual](https://bioconductor.org/packages/release/bioc/manuals/SeqArray/man/SeqArray.pdf)]. Then, FAVORannotator can annotate your GDS file into the annotated GDS (aGDS) files.

On another comment, the annotation database from FAVOR database (and FAVORdatabase_chrsplit.csv) is based on NCBI GRCh38/UCSC hg38. Given that your genotype data and its annotation are from plants, you may consider writing a customized wrapper and running [STAAR](https://github.com/xihaoli/STAAR) or [STAARpipeline](https://github.com/xihaoli/STAARpipeline) directly, as STAAR/STAARpipeline is a general method for phenotype-genotype association analysis.

Hope this helps.

Best,
Xihao
