### ISSUE TITLE
Results are not consistent with what we got before

### ISSUE THREAD

**Issue by akhilpampana** [xihaoli/STAARpipeline#7]
Hello, 

I have performed RVAS analysis using STAARpipeline using TOPMed dataset and got the results but when I performed the analysis on the updated dataset, I am not getting the same results as before and Genes that are reported as significant in the original analysis is not significant or not present in the results files. Can you help me out regarding this?

Thank you so much for help.

**Comment by xihaoli** [comment]
Hi Akhil,

Thanks for letting me know. For TOPMed-related questions, please feel free to send us an email. We can discuss and address them.

Best,
Xihao
