### ISSUE TITLE
Running docker image 

### ISSUE THREAD

**Issue by GACGAMA** [xihaoli/STAARpipeline#8]
Hi everyone!
Is there any possibility of providing a small tutorial on how to use the docker image from STAAR-pipeline?
Without any directions I'm not sure how to execute the correct steps with it and I'm not sure how to proceed. I'm working on implementing the staar-pipeline for our cluster and the docker image would be the best way to do so.
Thanks

**Comment by zilinli1988** [comment]
The STAARpipeline docker image is hosted on the docker hub at https://hub.docker.com/r/zilinli/staarpipeline. It depends on whether your cluster supports for docker image. For example, in the Harvard FAS cluster, we could use a docker image by using singularity. Please see the following tutorial for details: https://docs.rc.fas.harvard.edu/kb/singularity-on-the-cluster/. After we have the sif file of our STAARpipeline Docker image in the Harvard FAS cluster, please see the following code for an example:  

```
### Example 1: use sif to run an interactive R
salloc -p test -n 1 -t 00-08:00 --mem=60000 singularity shell staarpipeline_0.9.6.sif
R

### Example 2: use sif to run a single R script
salloc -p test -n 1 -t 00-08:00 --mem=60000
singularity shell staarpipeline_0.9.6.sif
R CMD BATCH Association_Analysis_PreStep.r
```

**Comment by GACGAMA** [comment]
Thanks for the examples! They will be very helpful.
Is favorannotator also included in the docker image?

**Comment by zilinli1988** [comment]
Currently, favorannotator is not included in the docker image.
